REM INSERTING into PWMNRPT.FIN_DASH_SALE_OI_CHART
SET DEFINE OFF;
Insert into PWMNRPT.FIN_DASH_SALE_OI_CHART (EXT_OGE_OI,SALE_OI,CREATED_BY,CREATED_DATE) values ('EXT','Sale','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_SALE_OI_CHART (EXT_OGE_OI,SALE_OI,CREATED_BY,CREATED_DATE) values ('OGE','Sale','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_SALE_OI_CHART (EXT_OGE_OI,SALE_OI,CREATED_BY,CREATED_DATE) values ('OI','OI','Appplication',to_date('09-JUN-16','DD-MON-RR'));
commit;
