--------------------------------------------------------
--  File created - Saturday-June-25-2016   
--------------------------------------------------------
REM INSERTING into PWMNRPT.FIN_DASH_TIMELINE_CHART
SET DEFINE OFF;
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-JUL-16','DD-MON-RR'),'2Q','2016','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-AUG-16','DD-MON-RR'),'3Q','2016','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-SEP-16','DD-MON-RR'),'3Q','2016','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-OCT-16','DD-MON-RR'),'3Q','2016','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-NOV-16','DD-MON-RR'),'4Q','2016','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-DEC-16','DD-MON-RR'),'4Q','2016','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-JAN-17','DD-MON-RR'),'4Q','2016','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-FEB-17','DD-MON-RR'),'1Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-MAR-17','DD-MON-RR'),'1Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-APR-17','DD-MON-RR'),'1Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-MAY-17','DD-MON-RR'),'2Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-JUN-17','DD-MON-RR'),'2Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-JUL-17','DD-MON-RR'),'2Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-AUG-17','DD-MON-RR'),'3Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-SEP-17','DD-MON-RR'),'3Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-OCT-17','DD-MON-RR'),'3Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-NOV-17','DD-MON-RR'),'4Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-DEC-17','DD-MON-RR'),'4Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-JAN-18','DD-MON-RR'),'4Q','2017','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-FEB-18','DD-MON-RR'),'1Q','2018','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-MAR-18','DD-MON-RR'),'1Q','2018','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-APR-18','DD-MON-RR'),'1Q','2018','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-MAY-18','DD-MON-RR'),'2Q','2018','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-JUN-18','DD-MON-RR'),'2Q','2018','Appplication',to_date('09-JUN-16','DD-MON-RR'));
Insert into PWMNRPT.FIN_DASH_TIMELINE_CHART (TIME_OF_LOAD,QUARTER,YEAR,CREATED_BY,CREATED_DATE) values (to_date('01-JUL-18','DD-MON-RR'),'2Q','2018','Appplication',to_date('09-JUN-16','DD-MON-RR'));
