/*
 * Created on 23 May 2016 ( Time 00:58:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ge.power.findashboard.vo;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'UserMaster' entity
 * 
 * @author Telosys Tools
 *
 */
public class UserVO implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : USER_SSO NUMBER 
    private BigDecimal userSso;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : ROLE_ID NUMBER 
    private BigDecimal roleId;

    // DB : USER_FIRST_NAME VARCHAR2 
    private String userFirstName;

    // DB : USER_LAST_NAME VARCHAR2 
    private String userLastName;

    // DB : USER_EMAIL_ADDRESS VARCHAR2 
    private String userEmailAddress;

    // DB : ACTIVATED CHAR 
    private String activated;

    // DB : CREATED_BY VARCHAR2 
    private String createdBy;

    // DB : CREATED_DATE DATE 
    private Date createdDate;

    // DB : MODIFIED_BY VARCHAR2 
    private String modifiedBy;

    // DB : MODIFIED_DATE DATE 
    private Date modifiedDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUserSso( BigDecimal userSso ) {
        this.userSso = userSso ;
    }

    public BigDecimal getUserSso() {
        return this.userSso;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRoleId( BigDecimal roleId ) {
        this.roleId = roleId;
    }
    public BigDecimal getRoleId() {
        return this.roleId;
    }

    public void setUserFirstName( String userFirstName ) {
        this.userFirstName = userFirstName;
    }
    public String getUserFirstName() {
        return this.userFirstName;
    }

    public void setUserLastName( String userLastName ) {
        this.userLastName = userLastName;
    }
    public String getUserLastName() {
        return this.userLastName;
    }

    public void setUserEmailAddress( String userEmailAddress ) {
        this.userEmailAddress = userEmailAddress;
    }
    public String getUserEmailAddress() {
        return this.userEmailAddress;
    }

    public void setActivated( String activated ) {
        this.activated = activated;
    }
    public String getActivated() {
        return this.activated;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedDate( Date modifiedDate ) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(userSso);
        sb.append("|");
        sb.append(roleId);
        sb.append("|");
        sb.append(userFirstName);
        sb.append("|");
        sb.append(userLastName);
        sb.append("|");
        sb.append(userEmailAddress);
        sb.append("|");
        sb.append(activated);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(modifiedDate);
        return sb.toString(); 
    } 


}
