--------------------------------------------------------
--  File created - Saturday-June-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FIN_DASH_SGMNT_CHART
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_SGMNT_CHART" 
   (	"SEGMENT" VARCHAR2(10 BYTE), 
	"BUSINESS" VARCHAR2(15 BYTE), 
	"GE_ALSTOM" VARCHAR2(6 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINANCIALS_QUARTERLY_VW
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINANCIALS_QUARTERLY_VW" 
   (	"PROJECT_ID" VARCHAR2(20 BYTE), 
	"VERSION_ID" NUMBER(20,0), 
	"REV4Q15" VARCHAR2(30 BYTE), 
	"REV1Q16" VARCHAR2(30 BYTE), 
	"REV2Q16" VARCHAR2(30 BYTE), 
	"REV3Q16" VARCHAR2(30 BYTE), 
	"REV4Q16" VARCHAR2(30 BYTE), 
	"OM4Q15" VARCHAR2(30 BYTE), 
	"OM1Q16" VARCHAR2(30 BYTE), 
	"OM2Q16" VARCHAR2(30 BYTE), 
	"OM3Q16" VARCHAR2(30 BYTE), 
	"OM4Q16" VARCHAR2(30 BYTE), 
	"CI4Q15" VARCHAR2(30 BYTE), 
	"CI1Q16" VARCHAR2(30 BYTE), 
	"CI2Q16" VARCHAR2(30 BYTE), 
	"CI3Q16" VARCHAR2(30 BYTE), 
	"CI4Q16" VARCHAR2(30 BYTE), 
	"INV4Q15" VARCHAR2(30 BYTE), 
	"INV1Q16" VARCHAR2(30 BYTE), 
	"INV2Q16" VARCHAR2(30 BYTE), 
	"INV3Q16" VARCHAR2(30 BYTE), 
	"INV4Q16" VARCHAR2(30 BYTE), 
	"AHC4Q15" VARCHAR2(30 BYTE), 
	"AHC1Q16" VARCHAR2(30 BYTE), 
	"AHC2Q16" VARCHAR2(30 BYTE), 
	"AHC3Q16" VARCHAR2(30 BYTE), 
	"AHC4Q16" VARCHAR2(30 BYTE), 
	"GEHC4Q15" VARCHAR2(30 BYTE), 
	"GEHC1Q16" VARCHAR2(30 BYTE), 
	"GEHC2Q16" VARCHAR2(30 BYTE), 
	"GEHC3Q16" VARCHAR2(30 BYTE), 
	"GEHC4Q16" VARCHAR2(30 BYTE), 
	"CTHC4Q15" VARCHAR2(30 BYTE), 
	"CTHC1Q16" VARCHAR2(30 BYTE), 
	"CTHC2Q16" VARCHAR2(30 BYTE), 
	"CTHC3Q16" VARCHAR2(30 BYTE), 
	"CTHC4Q16" VARCHAR2(30 BYTE), 
	"CNS4Q15" VARCHAR2(30 BYTE), 
	"CNS1Q16" VARCHAR2(30 BYTE), 
	"CNS2Q16" VARCHAR2(30 BYTE), 
	"CNS3Q16" VARCHAR2(30 BYTE), 
	"CNS4Q16" VARCHAR2(30 BYTE), 
	"CAHC4Q15" VARCHAR2(30 BYTE), 
	"CAHC1Q16" VARCHAR2(30 BYTE), 
	"CAHC2Q16" VARCHAR2(30 BYTE), 
	"CAHC3Q16" VARCHAR2(30 BYTE), 
	"CAHC4Q16" VARCHAR2(30 BYTE), 
	"CGEHC4Q15" VARCHAR2(30 BYTE), 
	"CGEHC1Q16" VARCHAR2(30 BYTE), 
	"CGEHC2Q16" VARCHAR2(30 BYTE), 
	"CGEHC3Q16" VARCHAR2(30 BYTE), 
	"CGEHC4Q16" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 1024000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" 
  PARALLEL ;
--------------------------------------------------------
--  DDL for Table FINANCIALS_YEARLY
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINANCIALS_YEARLY" 
   (	"PROJECT_ID" VARCHAR2(20 BYTE), 
	"VERSION_ID" NUMBER(20,0), 
	"FINANCIAL_NAME_CODE" NUMBER(3,0), 
	"YEAR" VARCHAR2(10 BYTE), 
	"VALUE" VARCHAR2(30 BYTE), 
	"USER_IDENTIFIER" NUMBER(5,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 1024000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FIN_DASH_BATCH_TRACKER
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_BATCH_TRACKER" 
   (	"BATCH_ID" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"STATUS_CODE" VARCHAR2(2 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_ALERT
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_ALERT" 
   (	"ALERT_ID" NUMBER, 
	"SHORT_DESC" VARCHAR2(100 BYTE), 
	"FULL_DESC" VARCHAR2(3500 BYTE), 
	"CUSTOM_MESSAGE" VARCHAR2(3500 BYTE), 
	"SEVERITY" NUMBER, 
	"RUN" NUMBER, 
	"R_DATE" DATE, 
	"R_MONTH" NUMBER, 
	"R_QUARTER" NUMBER, 
	"R_YEAR" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FIN_DASH_TIMELINE_CHART
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_TIMELINE_CHART" 
   (	"TIME_OF_LOAD" DATE, 
	"QUARTER" VARCHAR2(2 BYTE), 
	"YEAR" VARCHAR2(10 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FIN_DASH_SALE_OI_CHART
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_SALE_OI_CHART" 
   (	"EXT_OGE_OI" VARCHAR2(6 BYTE), 
	"SALE_OI" VARCHAR2(6 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table CLOSING_OPERATIONS_AGG_BKP
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."CLOSING_OPERATIONS_AGG_BKP" 
   (	"CLOSE_OP_KEY" NUMBER, 
	"R_DATE" DATE, 
	"R_MONTH" VARCHAR2(10 BYTE), 
	"R_QUARTER" VARCHAR2(3 BYTE), 
	"R_YEAR" NUMBER, 
	"GRAIN_IND" VARCHAR2(2 BYTE), 
	"JE_LINES" NUMBER, 
	"L_RUNS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FIN_DASH_PACING1
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_PACING1" 
   (	"PROJECT_ID" VARCHAR2(50 BYTE), 
	"PROJECT_NAME" VARCHAR2(100 BYTE), 
	"BUSINESS" VARCHAR2(20 BYTE), 
	"SUB_BUSINESS" VARCHAR2(40 BYTE), 
	"CUSTOMER" VARCHAR2(100 BYTE), 
	"COUNTRY_US_STATE" VARCHAR2(40 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"GGO_COUNTRY" VARCHAR2(40 BYTE), 
	"GGO_SUB_REGION" VARCHAR2(30 BYTE), 
	"DR14B_COUNTRY" VARCHAR2(40 BYTE), 
	"GE_ALSTOM" VARCHAR2(10 BYTE), 
	"SEGMENT" VARCHAR2(20 BYTE), 
	"YEAR" VARCHAR2(10 BYTE), 
	"QUARTER" VARCHAR2(5 BYTE), 
	"GE_CONTRACT_CODE" VARCHAR2(10 BYTE), 
	"EQUIP_SERV" VARCHAR2(10 BYTE), 
	"IPS" VARCHAR2(20 BYTE), 
	"SALE_OI" VARCHAR2(10 BYTE), 
	"COUNTRY_OF_ORIGIN" VARCHAR2(40 BYTE), 
	"USEXPORT_DOM_INTL" VARCHAR2(15 BYTE), 
	"EXT_OGE_OI" VARCHAR2(5 BYTE), 
	"UNIT_COUNT" VARCHAR2(50 BYTE), 
	"ORDER_SALE" VARCHAR2(50 BYTE), 
	"ORDER_SALE_MARGIN" VARCHAR2(50 BYTE), 
	"ORDER_SALE_MARGIN_PCT" VARCHAR2(50 BYTE), 
	"VERSION_ID" NUMBER, 
	"BATCH_ID" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FIN_DASH_REGION_MAPPING
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_REGION_MAPPING" 
   (	"COUNTRY_STATE" VARCHAR2(50 BYTE), 
	"DR14B_COUNTRY" VARCHAR2(50 BYTE), 
	"GGO_SUB_REGIONS" VARCHAR2(50 BYTE), 
	"GGO_COUNTRY" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FIN_DASH_PACING_STG
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_PACING_STG" 
   (	"PROJECT_ID" VARCHAR2(50 BYTE), 
	"PROJECT_NAME" VARCHAR2(100 BYTE), 
	"SUB_BUSINESS" VARCHAR2(40 BYTE), 
	"CUSTOMER" VARCHAR2(100 BYTE), 
	"COUNTRY_US_STATE" VARCHAR2(40 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"SEGMENT" VARCHAR2(20 BYTE), 
	"GE_CONTRACT_CODE" VARCHAR2(10 BYTE), 
	"EQUIP_SERV" VARCHAR2(10 BYTE), 
	"IPS" VARCHAR2(20 BYTE), 
	"COUNTRY_OF_ORIGIN" VARCHAR2(40 BYTE), 
	"USEXPORT_DOM_INTL" VARCHAR2(15 BYTE), 
	"EXT_OGE_OI" VARCHAR2(5 BYTE), 
	"UNIT_COUNT" VARCHAR2(50 BYTE), 
	"ORDER_SALE" VARCHAR2(50 BYTE), 
	"ORDER_SALE_MARGIN" VARCHAR2(50 BYTE), 
	"VERSION_ID" NUMBER, 
	"BATCH_ID" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FIN_DASH_PACING
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_PACING" 
   (	"PROJECT_ID" VARCHAR2(50 BYTE), 
	"PROJECT_NAME" VARCHAR2(100 BYTE), 
	"BUSINESS" VARCHAR2(20 BYTE), 
	"SUB_BUSINESS" VARCHAR2(40 BYTE), 
	"CUSTOMER" VARCHAR2(100 BYTE), 
	"COUNTRY_US_STATE" VARCHAR2(40 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"GGO_COUNTRY" VARCHAR2(40 BYTE), 
	"GGO_SUB_REGION" VARCHAR2(30 BYTE), 
	"DR14B_COUNTRY" VARCHAR2(40 BYTE), 
	"GE_ALSTOM" VARCHAR2(10 BYTE), 
	"SEGMENT" VARCHAR2(20 BYTE), 
	"YEAR" VARCHAR2(10 BYTE), 
	"QUARTER" VARCHAR2(5 BYTE), 
	"GE_CONTRACT_CODE" VARCHAR2(10 BYTE), 
	"EQUIP_SERV" VARCHAR2(10 BYTE), 
	"IPS" VARCHAR2(20 BYTE), 
	"SALE_OI" VARCHAR2(10 BYTE), 
	"COUNTRY_OF_ORIGIN" VARCHAR2(40 BYTE), 
	"USEXPORT_DOM_INTL" VARCHAR2(15 BYTE), 
	"EXT_OGE_OI" VARCHAR2(5 BYTE), 
	"UNIT_COUNT" VARCHAR2(50 BYTE), 
	"ORDER_SALE" VARCHAR2(50 BYTE), 
	"ORDER_SALE_MARGIN" VARCHAR2(50 BYTE), 
	"ORDER_SALE_MARGIN_PCT" VARCHAR2(50 BYTE), 
	"VERSION_ID" NUMBER, 
	"BATCH_ID" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FIN_DASH_PACING_ERR_CHK
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FIN_DASH_PACING_ERR_CHK" 
   (	"BATCH_ID" VARCHAR2(50 BYTE), 
	"PROJECT_NAME" VARCHAR2(100 BYTE), 
	"SEGMENT" VARCHAR2(20 BYTE), 
	"SEG_ERR_CHK" NUMBER, 
	"EXT_OGE_OI" VARCHAR2(5 BYTE), 
	"EXT_ERR_CHK" NUMBER, 
	"EQUIP_SERV" VARCHAR2(10 BYTE), 
	"EQP_SRV_ERR_CHK" NUMBER, 
	"COUNTRY_US_STATE" VARCHAR2(40 BYTE), 
	"CNTRY_ERR_CHK" NUMBER, 
	"ERR_CHK_KEY" NUMBER, 
	"OI_O_MARGIN" VARCHAR2(50 BYTE), 
	"OI_O_MRGN_ERR_CHK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINANCIALS_YEARLY_VW
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINANCIALS_YEARLY_VW" 
   (	"PROJECT_ID" VARCHAR2(20 BYTE), 
	"VERSION_ID" NUMBER(20,0), 
	"REVFY15" VARCHAR2(30 BYTE), 
	"REVFY16" VARCHAR2(30 BYTE), 
	"REVFY17" VARCHAR2(30 BYTE), 
	"REVFY18" VARCHAR2(30 BYTE), 
	"REVFY19" VARCHAR2(30 BYTE), 
	"REVFY20" VARCHAR2(30 BYTE), 
	"OMFY15" VARCHAR2(30 BYTE), 
	"OMFY16" VARCHAR2(30 BYTE), 
	"OMFY17" VARCHAR2(30 BYTE), 
	"OMFY18" VARCHAR2(30 BYTE), 
	"OMFY19" VARCHAR2(30 BYTE), 
	"OMFY20" VARCHAR2(30 BYTE), 
	"CIFY15" VARCHAR2(30 BYTE), 
	"CIFY16" VARCHAR2(30 BYTE), 
	"CIFY17" VARCHAR2(30 BYTE), 
	"CIFY18" VARCHAR2(30 BYTE), 
	"CIFY19" VARCHAR2(30 BYTE), 
	"CIFY20" VARCHAR2(30 BYTE), 
	"INVFY15" VARCHAR2(30 BYTE), 
	"INVFY16" VARCHAR2(30 BYTE), 
	"INVFY17" VARCHAR2(30 BYTE), 
	"INVFY18" VARCHAR2(30 BYTE), 
	"INVFY19" VARCHAR2(30 BYTE), 
	"INVFY20" VARCHAR2(30 BYTE), 
	"AHCFY15" VARCHAR2(30 BYTE), 
	"AHCFY16" VARCHAR2(30 BYTE), 
	"AHCFY17" VARCHAR2(30 BYTE), 
	"AHCFY18" VARCHAR2(30 BYTE), 
	"AHCFY19" VARCHAR2(30 BYTE), 
	"AHCFY20" VARCHAR2(30 BYTE), 
	"GEHCFY15" VARCHAR2(30 BYTE), 
	"GEHCFY16" VARCHAR2(30 BYTE), 
	"GEHCFY17" VARCHAR2(30 BYTE), 
	"GEHCFY18" VARCHAR2(30 BYTE), 
	"GEHCFY19" VARCHAR2(30 BYTE), 
	"GEHCFY20" VARCHAR2(30 BYTE), 
	"CTHCFY15" VARCHAR2(30 BYTE), 
	"CTHCFY16" VARCHAR2(30 BYTE), 
	"CTHCFY17" VARCHAR2(30 BYTE), 
	"CTHCFY18" VARCHAR2(30 BYTE), 
	"CTHCFY19" VARCHAR2(30 BYTE), 
	"CTHCFY20" VARCHAR2(30 BYTE), 
	"CNSFY15" VARCHAR2(30 BYTE), 
	"CNSFY16" VARCHAR2(30 BYTE), 
	"CNSFY17" VARCHAR2(30 BYTE), 
	"CNSFY18" VARCHAR2(30 BYTE), 
	"CNSFY19" VARCHAR2(30 BYTE), 
	"CNSFY20" VARCHAR2(30 BYTE), 
	"CAHCFY15" VARCHAR2(30 BYTE), 
	"CAHCFY16" VARCHAR2(30 BYTE), 
	"CAHCFY17" VARCHAR2(30 BYTE), 
	"CAHCFY18" VARCHAR2(30 BYTE), 
	"CAHCFY19" VARCHAR2(30 BYTE), 
	"CAHCFY20" VARCHAR2(30 BYTE), 
	"CGEHCFY15" VARCHAR2(30 BYTE), 
	"CGEHCFY16" VARCHAR2(30 BYTE), 
	"CGEHCFY17" VARCHAR2(30 BYTE), 
	"CGEHCFY18" VARCHAR2(30 BYTE), 
	"CGEHCFY19" VARCHAR2(30 BYTE), 
	"CGEHCFY20" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 1024000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" 
  PARALLEL ;
--------------------------------------------------------
--  DDL for Table FINANCIALS_QUARTERLY
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINANCIALS_QUARTERLY" 
   (	"PROJECT_ID" VARCHAR2(20 BYTE), 
	"VERSION_ID" NUMBER(20,0), 
	"FINANCIAL_NAME_CODE" NUMBER(3,0), 
	"QUARTER" VARCHAR2(10 BYTE), 
	"VALUE" VARCHAR2(30 BYTE), 
	"USER_IDENTIFIER" NUMBER(5,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 1024000 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINANCIALS_NAME
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINANCIALS_NAME" 
   (	"FINANCIAL_NAME_CODE" NUMBER(3,0), 
	"FINANCIAL_NAME" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 24576 NEXT 1024000
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_CLOSING_FINANCE_PLAN
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_CLOSING_FINANCE_PLAN" 
   (	"R_MONTH" VARCHAR2(10 BYTE), 
	"R_QUARTER" VARCHAR2(3 BYTE), 
	"R_YEAR" NUMBER, 
	"GRAIN_IND" VARCHAR2(2 BYTE), 
	"REVENUE_PLAN" NUMBER, 
	"ORDERS_PLAN" NUMBER, 
	"OP_PLAN" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_CLOSING_FINANCIALS_AGG
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_CLOSING_FINANCIALS_AGG" 
   (	"C_ID" VARCHAR2(5 BYTE), 
	"C_DATE" DATE, 
	"C_MONTH" VARCHAR2(10 BYTE), 
	"QUARTER" VARCHAR2(3 BYTE), 
	"C_YEAR" NUMBER, 
	"KPI" VARCHAR2(50 BYTE), 
	"ACTUALS" NUMBER, 
	"GOAL" NUMBER, 
	"TARGET" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_CLOSING_FINANCIALS_RAW
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_CLOSING_FINANCIALS_RAW" 
   (	"C_ID" VARCHAR2(5 BYTE), 
	"C_DATE" DATE, 
	"C_MONTH" VARCHAR2(10 BYTE), 
	"QUARTER" VARCHAR2(3 BYTE), 
	"C_YEAR" NUMBER, 
	"KPI" VARCHAR2(50 BYTE), 
	"SECTION" VARCHAR2(10 BYTE), 
	"ACTUALS" NUMBER, 
	"GOAL" NUMBER, 
	"TARGET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_CLOSING_FINANCIALS_STG
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_CLOSING_FINANCIALS_STG" 
   (	"C_ID" VARCHAR2(10 BYTE), 
	"C_DATE" DATE, 
	"C_MONTH" NUMBER, 
	"QUARTER" VARCHAR2(3 BYTE), 
	"KPI" VARCHAR2(50 BYTE), 
	"ACTUALS" NUMBER, 
	"GOAL" NUMBER, 
	"TARGET" NUMBER, 
	"R_YEAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_CLOSING_OPER_PLAN
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_CLOSING_OPER_PLAN" 
   (	"R_DATE" DATE, 
	"R_MONTH" VARCHAR2(10 BYTE), 
	"R_QUARTER" VARCHAR2(3 BYTE), 
	"R_YEAR" NUMBER, 
	"GRAIN_IND" VARCHAR2(2 BYTE), 
	"JE_LINES_PLAN" NUMBER, 
	"L_RUNS_PLAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_CLOSING_OPERATIONS_AGG
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_CLOSING_OPERATIONS_AGG" 
   (	"CLOSE_OP_KEY" NUMBER, 
	"R_DATE" DATE, 
	"R_MONTH" VARCHAR2(10 BYTE), 
	"R_QUARTER" VARCHAR2(3 BYTE), 
	"R_YEAR" NUMBER, 
	"GRAIN_IND" VARCHAR2(2 BYTE), 
	"JE_LINES" NUMBER, 
	"L_RUNS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_CLOSING_RUN_STATUS
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_CLOSING_RUN_STATUS" 
   (	"R_DATE" DATE, 
	"R_MONTH_NUM" NUMBER, 
	"R_QUARTER" VARCHAR2(3 BYTE), 
	"R_YEAR" NUMBER, 
	"R_SOURCE" VARCHAR2(30 BYTE), 
	"RUN_NUM" NUMBER(*,0), 
	"STATUS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_CLOSING_SCHEDULES
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_CLOSING_SCHEDULES" 
   (	"SCH_NAME" VARCHAR2(50 BYTE), 
	"SCH_DESC" VARCHAR2(200 BYTE), 
	"SCH_TIME" VARCHAR2(50 BYTE), 
	"R_DATE" DATE, 
	"R_MONTH" NUMBER, 
	"R_QUARTER" VARCHAR2(3 BYTE), 
	"R_YEAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_MESSAGE
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_MESSAGE" 
   (	"MESSAGE_ID" NUMBER, 
	"SHORT_DESC" VARCHAR2(100 BYTE), 
	"FULL_DESC" VARCHAR2(3500 BYTE), 
	"RUN" NUMBER, 
	"R_DATE" DATE, 
	"R_MONTH" NUMBER, 
	"R_QUARTER" NUMBER, 
	"R_YEAR" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_PROCESSING_RATE
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_PROCESSING_RATE" 
   (	"PROC_RATE_ID" NUMBER, 
	"TOTAL_RECORDS" NUMBER, 
	"PROCESSING_TIME" NUMBER, 
	"RECORDS_PER_MINUTE" NUMBER, 
	"RUN" NUMBER, 
	"R_DATE" DATE, 
	"R_MONTH" NUMBER, 
	"R_QUARTER" NUMBER, 
	"R_YEAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Table FINDASH_QUARTER
--------------------------------------------------------

  CREATE TABLE "PWMNRPT"."FINDASH_QUARTER" 
   (	"QUARTER" VARCHAR2(3 BYTE), 
	"R_YEAR" NUMBER, 
	"S_DATE" DATE, 
	"E_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" ;
--------------------------------------------------------
--  DDL for Index I_SNAP$_FINANCIALS_QUARTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PWMNRPT"."I_SNAP$_FINANCIALS_QUARTER" ON "PWMNRPT"."FINANCIALS_QUARTERLY_VW" (SYS_OP_MAP_NONNULL("PROJECT_ID"), SYS_OP_MAP_NONNULL("VERSION_ID")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" 
  PARALLEL ;
--------------------------------------------------------
--  DDL for Index ID_FK_FIN_YEARLY
--------------------------------------------------------

  CREATE INDEX "PWMNRPT"."ID_FK_FIN_YEARLY" ON "PWMNRPT"."FINANCIALS_YEARLY" ("PROJECT_ID", "VERSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_INDEXES" ;
--------------------------------------------------------
--  DDL for Index I_SNAP$_FINANCIALS_YEARLY_
--------------------------------------------------------

  CREATE UNIQUE INDEX "PWMNRPT"."I_SNAP$_FINANCIALS_YEARLY_" ON "PWMNRPT"."FINANCIALS_YEARLY_VW" (SYS_OP_MAP_NONNULL("PROJECT_ID"), SYS_OP_MAP_NONNULL("VERSION_ID")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_TABLES" 
  PARALLEL ;
--------------------------------------------------------
--  DDL for Index ID_FK_FIN_QRTRLY
--------------------------------------------------------

  CREATE INDEX "PWMNRPT"."ID_FK_FIN_QRTRLY" ON "PWMNRPT"."FINANCIALS_QUARTERLY" ("PROJECT_ID", "VERSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWMNRPT_INDEXES" ;
--------------------------------------------------------
--  DDL for Index FN_NME_CD_UC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PWMNRPT"."FN_NME_CD_UC" ON "PWMNRPT"."FINANCIALS_NAME" ("FINANCIAL_NAME_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "PWMNRPT_INDEXES" ;
--------------------------------------------------------
--  Constraints for Table FINANCIALS_QUARTERLY_VW
--------------------------------------------------------

  ALTER TABLE "PWMNRPT"."FINANCIALS_QUARTERLY_VW" MODIFY ("VERSION_ID" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_QUARTERLY_VW" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINANCIALS_YEARLY
--------------------------------------------------------

  ALTER TABLE "PWMNRPT"."FINANCIALS_YEARLY" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_YEARLY" MODIFY ("FINANCIAL_NAME_CODE" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_YEARLY" MODIFY ("VERSION_ID" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_YEARLY" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINANCIALS_YEARLY_VW
--------------------------------------------------------

  ALTER TABLE "PWMNRPT"."FINANCIALS_YEARLY_VW" MODIFY ("VERSION_ID" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_YEARLY_VW" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINANCIALS_QUARTERLY
--------------------------------------------------------

  ALTER TABLE "PWMNRPT"."FINANCIALS_QUARTERLY" MODIFY ("QUARTER" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_QUARTERLY" MODIFY ("FINANCIAL_NAME_CODE" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_QUARTERLY" MODIFY ("VERSION_ID" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_QUARTERLY" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINANCIALS_NAME
--------------------------------------------------------

  ALTER TABLE "PWMNRPT"."FINANCIALS_NAME" ADD CONSTRAINT "FN_NME_CD_UC" UNIQUE ("FINANCIAL_NAME_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "PWMNRPT_INDEXES"  ENABLE;
  ALTER TABLE "PWMNRPT"."FINANCIALS_NAME" MODIFY ("FINANCIAL_NAME" NOT NULL ENABLE);
  ALTER TABLE "PWMNRPT"."FINANCIALS_NAME" MODIFY ("FINANCIAL_NAME_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FINANCIALS_YEARLY
--------------------------------------------------------

  ALTER TABLE "PWMNRPT"."FINANCIALS_YEARLY" ADD CONSTRAINT "ID_YEARLY_FK" FOREIGN KEY ("PROJECT_ID", "VERSION_ID")
	  REFERENCES "PWMNRPT"."IDENTITY_DATA" ("PROJECT_ID", "VERSION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCIALS_QUARTERLY
--------------------------------------------------------

  ALTER TABLE "PWMNRPT"."FINANCIALS_QUARTERLY" ADD CONSTRAINT "ID_QUARTERLY_FK" FOREIGN KEY ("PROJECT_ID", "VERSION_ID")
	  REFERENCES "PWMNRPT"."IDENTITY_DATA" ("PROJECT_ID", "VERSION_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger FINDASH_BATCH_TRACKER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PWMNRPT"."FINDASH_BATCH_TRACKER" 
before insert
on Fin_Dash_Batch_Tracker
for each row
begin
select FinDash_Tracker.nextval
into :new.Batch_Id
from dual;
end;
/
ALTER TRIGGER "PWMNRPT"."FINDASH_BATCH_TRACKER" DISABLE;
--------------------------------------------------------
--  DDL for Trigger ERR_CHK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PWMNRPT"."ERR_CHK_TRG" 
before insert
on Fin_Dash_Pacing_Err_Chk
for each row
begin
select Err_Chk.nextval 
into :new.Err_Chk_Key
from dual;
end;
/
ALTER TRIGGER "PWMNRPT"."ERR_CHK_TRG" ENABLE;
